### ISSUE TITLE
duplicate row.names

### ISSUE THREAD

**Issue by pachadotdev** [Enchufa2/bspm#70] opened 2023-05-20 16:30 UTC
Hi

I could trace this error back to bspm https://github.com/r-lib/devtools/issues/2514.

When we want to install all the dependencies in the `DESCRIPTION`  with `devtools::install()`, the command fails. If we do `bspm::disable()`, then it works but builds everything from source.

Also `devtools::install_github("cienciadedatos/r4ds")` fails with the same message.

If we install dependencies one by one, then it works,

**Comment by pachadotdev** [comment] 2023-05-20 16:31
also,  I created this repo to configure Ubuntu to install binary packages and also to install RStudio with apt install rstudio (stable and daily) https://github.com/pachadotdev/r-packages-ubuntu

**Comment by Enchufa2** [comment] 2023-05-20 18:39
Thanks for the report. Duplicate of #67, fixed in #68. I'll make a new release.

**Comment by Enchufa2** [comment] 2023-05-20 21:59
On CRAN now.

**Comment by Enchufa2** [comment] 2023-05-21 12:36
Reopening so that @eddelbuettel can add a comment, because apparently GitHub is not allowing him to comment on the closed issue

**Comment by Enchufa2** [comment] 2023-05-21 14:02
Seems unrelated to the issue status. Closing.

**Closed by Enchufa2** 2023-05-21 14:02 UTC
Labels: duplicate
